name: The High Plaines Drifter
favicon: null
layout_spectrum: 0.24301
typography_spectrum: 0.19066
title: The High Plaines Drifter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79009990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#496ca2'
    - '#91a6c1'
    - '#cfd4da'
    - '#fefef4'
    - '#18191e'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
