name: The High Plaines Drifter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68042
title: The High Plaines Drifter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#496ca2'
    - '#91a6c1'
    - '#cfd4da'
    - '#fefef4'
    - '#18191e'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
